#!/usr/bin/env bash
# script automatically configures a new Ubuntu machine to make a 301-redirection.

# update packages
sudo apt-get update

# install Nginx
sudo apt-get -y install nginx

# Start Nginx
sudo service nginx start

# Configure uncomplicated firewall to Nginx
sudo ufw allow "Nginx HTTP"
sudo ufw --force enable

# Create index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

SERVER_CONFIG="
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}

	# Make a permanent redirection for /redirect_me
	location = /redirect_me {
		return 301 https://www.google.com;
	}
}"

# Write server configuration to the default site file
echo "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

# Test Nginx for Syntax errors
sudo nginx -t

# Restart Nginx
sudo service nginx restart
