#!/usr/bin/env bash
# script automatically configures a new Ubuntu machine to make a 301-redirection.

# update packages
sudo apt-get update

# install Nginx
sudo apt-get -y install nginx

# Start Nginx
sudo service nginx start

# Configure uncomplicated firewall to Nginx
sudo ufw allow "Nginx HTTP"
sudo ufw --force enable

# Create index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx for Syntax errors
sudo nginx -t

# Making a 301 permanent redirection.
r_string="    rewrite ^/redirect_me https://www.google.com permanent;"
sudo sed -i "/server_name _;/a \ \ \ \ $r_string" /etc/nginx/sites-available/default

# Test Nginx for Syntax errors
sudo nginx -t

# Restart Nginx
sudo service nginx restart
