#!/usr/bin/env bash
# script automatically configures a new Ubuntu machine to make a 301-redirection.

# update packages
sudo apt-get update

# install Nginx
sudo apt-get -y install nginx

# Configure uncomplicated firewall to Nginx
sudo ufw allow "Nginx HTTP"

# Create index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx for Syntax errors
sudo nginx -t

# Making a 301 permanent redirection.
r_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/SantosAndrewz permanent;"
sudo sed -i "s/server_name _;/$r_string/" /etc/nginx/sites-enabled/default

# Create a 404 customized 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_r="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_r/" /etc/nginx/sites-enabled/default


# Restart Nginx
sudo service nginx start
