#!/usr/bin/env bash
# a script which does ping an IP address passed as an argument

# checking if IP Address is provided.
if [ "$#" -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
