#!/usr/bin/env bash
# script that creates a PID file traps signals, indefinately displays messages
#  and deletes file on termination

file="/var/run/myscript.pid"

# creating the PID file
echo $$ > "$file"

# handling signals
# SIGTERM and SIGQUIT handler
trap 'echo "I hate the kill command"; rm -f "$file"; exit' SIGTERM SIGQUIT

# SIGINT handler
trap "echo 'Y U no love me?!'" SIGINT

# Indefinite loop
while true;
	do
		echo "To infinity and beyond"
		sleep 2
done
