#!/usr/bin/env bash
# an init script that manages manage_my_process script[start|stop|restart]

cmd="$1"

case "$cmd" in
	start)
		bash ./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
                if [ -e " /var/run/my_process.pid" ]; then
			pkill -f './manage_my_process' && rm /var/run/my_process.pid
			echo "manage_my_process stopped"
		fi
		;;
	restart)
		"$0" stop > /dev/null
		"$0" start > /dev/null
		echo "manage_my_process restarted"
		;;
	*)
		echo "manage_my_process {start|stop|restart}"
		;;
esac
