#!/usr/bin/env bash
# script displays "To infinity and beyond" indefinitely then "I am invincible!!!" on ^C.

# setting up a trap for SIGTERM
trap "echo 'I am invincible!!!'" SIGTERM

# Infinity loop
while true;
        do
                echo "To infinity and beyond"
                sleep 2
done
