#!/usr/bin/env bash
# script for changing IP Address in a host configuring it to another server.

# creating a copy from the original hosts file.
cp /etc/hosts ~/hosts.new

# modifying the hosts file with new file
sed -i s/127.0.0.1/127.0.0.2/ ~/host.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Overwriting the original hosts files with the new files
cp -f ~/hosts.new /etc/hosts
